# Project key in JIRA
jirakey: 'PRJT'
# Organisation or user name eg. https://github.com/myorg/myrepo
org: 'myorg'
reponame: 'myrepo'
# Issue state to import: 'all', 'open', 'closed'
state: 'all'
# Include Pull Requests?
include_pr: true
# https://github.com/settings/tokens
token: 'abcdef'
